name: 'Setup Nix with Devenv'
description: 'Install Determinate Nix, FlakeHub Cache, and Devenv with optional additional profiles'
author: 'Your Name'

inputs:
  additionalProfiles:
    description: 'Additional Nix profiles to install (space-separated, e.g., "nixpkgs#sccache nixpkgs#cachix")'
    required: false
    default: ''
  additionalUnfreeProfiles:
    description: 'Additional unfree Nix profiles to install (space-separated, e.g., "nixpkgs#terraform nixpkgs#claude-code")'
    required: false
    default: ''
  nix-extra-conf:
    description: 'Additional Nix configuration options'
    required: false
    default: |
      lazy-trees = true
      http-connections = 64
      max-substitution-jobs = 64
      fsync-metadata = false
      show-trace = true
      max-silent-time = 900
  wb-snapshot:
    description: 'Enable WarpBuild snapshot creation (opt-in)'
    required: false
    default: 'false'
  impatient-networking:
    description: 'Enable aggressive timeout and retry settings for faster CI (opt-out, enabled by default)'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set Impatient Networking Config
      if: ${{ inputs.impatient-networking == 'true' }}
      id: impatient-config
      shell: bash
      run: |
        cat << 'EOF' >> $GITHUB_OUTPUT
        config<<IMPATIENT_EOF
        # Networking: be impatient
        connect-timeout = 5
        stalled-download-timeout = 10
        download-attempts = 3

        # Avoid long negative-cache waits for narinfo lookups
        narinfo-cache-negative-ttl = 5

        # Don't waste time falling back to source if a substituter is down
        fallback = false
        IMPATIENT_EOF
        EOF

    - name: Install Nix
      uses: DeterminateSystems/determinate-nix-action@v3
      with:
        diagnostic-endpoint: ""
        extra-conf: |
          ${{ steps.impatient-config.outputs.config }}
          ${{ inputs.nix-extra-conf }}

    - name: Install Devenv
      shell: bash
      run: |
        nix profile add nixpkgs#devenv

    - name: Install Additional Profiles
      if: ${{ inputs.additionalProfiles != '' }}
      shell: bash
      run: |
        for profile in ${{ inputs.additionalProfiles }}; do
          echo "Installing profile: $profile"
          nix profile add "$profile"
        done

    - name: Install Additional Unfree Profiles
      if: ${{ inputs.additionalUnfreeProfiles != '' }}
      shell: bash
      run: |
        for profile in ${{ inputs.additionalUnfreeProfiles }}; do
          echo "Installing unfree profile: $profile"
          NIXPKGS_ALLOW_UNFREE=1 nix profile add "$profile" --impure
        done

    - name: Compute WarpBuild Snapshot Alias
      if: ${{ inputs.wb-snapshot == 'true' }}
      id: wb-alias
      shell: bash
      run: |
        WORKFLOW_FILE=$(basename "${{ github.workflow_ref }}" | sed 's/@.*//' | sed 's/\.ya\?ml$//')
        INPUTS_HASH=$(echo -n "${{ inputs.additionalProfiles }}${{ inputs.additionalUnfreeProfiles }}${{ inputs.nix-extra-conf }}" | sha256sum | cut -c1-8)
        ALIAS="${{ github.repository }}-${WORKFLOW_FILE}-${{ github.ref_name }}-${INPUTS_HASH}"
        ALIAS=$(echo "$ALIAS" | tr '/' '-' | tr ' ' '-' | tr '_' '-')
        echo "Creating WarpBuild snapshot with alias: $ALIAS"
        echo "alias=$ALIAS" >> $GITHUB_OUTPUT

    - name: Create WarpBuild Snapshot
      if: ${{ inputs.wb-snapshot == 'true' }}
      uses: WarpBuilds/snapshot-save@v1
      with:
        alias: ${{ steps.wb-alias.outputs.alias }}
        fail-on-error: true

    - name: Setup FlakeHub Cache
      uses: DeterminateSystems/flakehub-cache-action@v2

branding:
  icon: 'package'
  color: 'blue'
